#include <stdio.h>
#include <time.h>
#include <math.h>

#define MAX_NUM	100

int isPrime(int number);

/* Project Euler Problem 29 */
int main()
{
    double timeTaken;
    clock_t start, end;
    start = clock();

    int totalTerms = (MAX_NUM - 1) * (MAX_NUM - 1);

    /* Set up the list of bases. */
    int marked[MAX_NUM - 1][3];
    int i, j, base = 2;
    for(i = 0; i < MAX_NUM - 1; i++)
    {
	marked[i][0] = 1;
	marked[i][1] = base++;
	marked[i][2] = 0;
    }

    /* Mark the powers. */
    int power;
    for(i = 0; marked[i][1] * marked[i][1] <= MAX_NUM; i++)
    {
	if(marked[i][0] == 1)
	{
	    int count = 1;
	    power = marked[i][1];
	    while(power <= MAX_NUM)
	    {
		power *= marked[i][1];
		for(j = 0; j < power; j++)
		{
		    if(marked[j][1] == power)
		    {
			marked[j][0] = ++count;
			marked[j][2] = marked[i][1];		    
			break;
		    }
		}
	    }
	}
    }

    /* Run through the numbers list and fill the values array based on the exponent position, e.g. 2^2 would result in 1 x 4 = 4, 4^2 is 2 x 2, etc. */
    int values[MAX_NUM - 1][MAX_NUM - 1];
    int exponent;
    for(i = 0; i < MAX_NUM - 1; i++)
    {
	exponent = 2;
	for(j = 0; j < MAX_NUM - 1; j++)
	{
	    values[i][j] = marked[i][0] * exponent++;
	}
    }

    /* Search through the grid for matches. */
    int k;
    for(i = 0; i < MAX_NUM - 1; i++)
    {
	if(marked[i][0] > 1)
	{
	    int checkRow = marked[i][2] - 2;
	    for(j = 0; j < MAX_NUM - 1; j++)
	    {
		for(k = 0; k < MAX_NUM - 1; k++)
		{
		    if(values[i][j] == values[checkRow][k])
		    {
			totalTerms--;
			checkRow = marked[i][2] - 2;
			break;
		    }
		    else if(k == MAX_NUM - 2)
		    {
			/* Switch to next power row higher up. */
			checkRow = (marked[checkRow][1] * marked[i][2]) - 2;
			k = 0;
			if(checkRow + 2 >= marked[i][1])
			{
			    checkRow = marked[i][2] - 2;
			    break;
			}
		    }
		}
	    }
	}
    }

    printf("The number of distinct terms in the sequence generated by a^b for 2 <= a <= %d and 2 <= b <= %d is %d.", MAX_NUM, MAX_NUM, totalTerms);

    end = clock();
    timeTaken = (double)(end - start) / CLOCKS_PER_SEC;
    printf("\nProgram execution time took %f seconds.\n", timeTaken);
    return 0;
}
