#include <stdio.h>
#include <math.h>

#define MAX_NUM	100

int isPrime(int number);
int isPower(int number, int numbers);

int main()
{
	double timeTaken;
    clock_t start, end;
    start = clock();

	int total = 0;
	int numbers[MAX_NUM - 1];

	int arrayCount;
	for(arrayCount = 0; arrayCount <= MAX_NUM; arrayCount++)
	{
		numbers[arrayCount] = arrayCount + 2;
	}

	/* Count from 2 to the maximum number. */
	int mainCount;
	for(mainCount = 2; mainCount <= MAX_NUM; mainCount++)
	{
		/* Check if the current number is prime and every number if so. */
		if(isPrime(mainCount))
		{
			total += MAX_NUM;
		}
		/* Check if the current number is power of previous number. */
		else if(isPower(mainCount, numbers))
		{

		}
		else
		{
			total += MAX_NUM;
		}
	}

	printf("The number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 is %d", total);

	end = clock();
    timeTaken = (double)(end - start) / CLOCKS_PER_SEC;
    printf("\nProgram execution time took %f seconds.\n", timeTaken);
    return 0;
}

/* Check if a number is prime. */
int isPrime(int number)
{
	if(number == 2)
	{
		return 1;
	}

	int root = (int)(ceil(sqrt(number)));

	int primeCount;
	for(primeCount = 2; primeCount <= root; primeCount++)
	{
		/* If it divides evenly, it is not prime. */
		if(number % primeCount == 0)
		{
			return 0;
		}
	}

	return 1;
}

/* Check if a number is a power of a previous number. */
int isPower(int number, int numbers)
{
	

	return 0;
}